function httpGet(theUrl){
    var xmlHttp = null;
    xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false );
    xmlHttp.send( null );
    return xmlHttp.responseText;
}

function createHeapChart(){
    var heap = JSON.parse(httpGet("/heap/"));
    var timestamps = JSON.parse(httpGet("/timestamps/"));

    var options = {
        rangeSelector : {
            selected : 1
        },

        title : {
            text : 'Max Heap Usage during profiling'
        },
        legend:{
            enabled :true
        },
        xAxis:{
            dateTimeLabelFormats: {
                millisecond: '%S.%L',
                second: '%H:%M:%S',
                minute: '%H:%M',
                hour: '%H:%M',
                day: '%e. %b',
                week: '%e. %b',
                month: '%b \'%y',
                year: '%Y'
            }
        },
        series : [{
            name : 'Heap Usage',
            data : heap.data,
            type : 'area',
            threshold : null,
            tooltip : {
                valueDecimals : 2
            },
            fillColor : {
                linearGradient : {
                    x1: 0, 
                    y1: 0, 
                    x2: 0, 
                    y2: 1
                },
                stops : [[0, Highcharts.getOptions().colors[0]], [1, 'rgba(0,0,0,0)']]
            }
        }]
    };

    var lastTime = 0;
    for(var i=0; i<timestamps.data.length;i++){
        var serie = {
            name : timestamps.legend[i],
            data: [[lastTime,heap.max], [timestamps.data[i],heap.max]],
            type : 'area',
            threshold : null,
            tooltip : {
                valueDecimals : 2
            },
            //fillColor: "green"
            fillOpacity: 0.2
        };
        options.series.push(serie);
        lastTime = timestamps.data[i];
    }
    $('#heap_chart').highcharts('StockChart', options);
}

function createFunctionTimeChart(){
    var time = JSON.parse(httpGet("/functionstime/"));
    $('#time_chart').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Time spent by javascript operations [%]'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    color: '#000000',
                    connectorColor: '#000000',
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                },
                showInLegend: true
            }
        },
        series: [{
            type: 'pie',
            name: '% time',
            data: time
        }]
    });
}

function createRPCNumberChart(){
    var rpc_frequency = JSON.parse(httpGet("/rpcfrequency/"));
    $('#rpc_frequency_chart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Number of exchanged RPCs'
        },
        xAxis: {
            categories: rpc_frequency.categories
        },
        yAxis: {
            min: 0,
            title: {
                text: 'RPC messages'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: '#RPCs',
            data: rpc_frequency.data
        }]
    });
}

function createRPCTrafficChart(){
    var rpc_traffic = JSON.parse(httpGet("/rpctraffic/"));
    $('#rpc_traffic_chart').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Network traffic generated by RPCs'
        },
        xAxis: {
            categories: rpc_traffic.categories
        },
        yAxis: {
            min: 0,
            title: {
                text: 'bytes'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Bytes',
            data: rpc_traffic.data
        }]
    });
}

function startReport(){
    createHeapChart();
    createFunctionTimeChart();
    createRPCNumberChart();
    createRPCTrafficChart();
}